[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"

# Enable CORS headers
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
